php:
    build: ./docker/php
    # image: php:7-fpm
    volumes:
        - .:/var/www/html
    ports:
        - "9000:9000"

nginx:
    image: nginx

    ports:
        - "8000:80"
    volumes:
        - ./docker/nginx/silex-template.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
        - php
    links:
        - php:php

